### ISSUE TITLE
Bug: yeoman won't finish generation because .gitignore is missing

### ISSUE THREAD

**Issue by vhfmag** [dodevops/yeoman-generator-typescript#1]
When I tried to generate a module I got the following error:
`AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: .../node/v8.8.1/lib/node_modules/generator-dodevops-typescript/generators/app/templates/static/.gitignore`

I just created an empty .gitignore file to get the generator to work, but thought it would be better to report the bug. Thanks! :)

**Comment by dploeger** [comment]
Yes, thanks for the report. Very strange. I guess, npm doesn't publish .gitignore files. I'll change the workflow there.
